from transformers import pipeline

def setup_qa_pipeline():
    """
    Set up the question-answering pipeline with a compatible model.
    
    Returns:
        pipeline: The question-answering pipeline.
    """
    return pipeline("question-answering", model="distilbert-base-cased-distilled-squad")

def generate_response(sections, query):
    """
    Generate a response to a query based on the retrieved sections.
    
    Args:
        sections (list of dict): List of retrieved sections with text.
        query (str): The query string.
    
    Returns:
        str: The answer generated by the QA model.
    """
    qa_pipeline = setup_qa_pipeline()

    # Combine all retrieved section texts
    combined_context = " ".join(section['text'] for section in sections)

    if not combined_context:
        raise ValueError("The combined context is empty. Please check the retrieved sections.")
    
    result = qa_pipeline(question=query, context=combined_context)
    return result['answer']
